### ISSUE TITLE
Memory Swapping

### ISSUE THREAD

**Issue by schdief06** [IBM/tensorflow-large-model-support#35] opened 2020-05-05 08:02 UTC
Hi,

after switching to a Ubuntu machine i finally managed to install tensorflow lms correctly.

Now I'm facing a new problem. As I'm working with big models on a rather small machine (6GB GPU RAM, 8GB CPU RAM) I'd like to use my swap partition. Is there a way to enable this?

Thanks for helping!

**Comment by mtbrandy** [comment] 2020-05-05 14:27
This is a duplicate of https://github.com/IBM/tensorflow-large-model-support/issues/33.  See the discussion there for more information.

**Closed as completed by mtbrandy** 2020-05-05 14:27 UTC
