### ISSUE TITLE
SystemError: <built-in function len> returned a result with an error set

### ISSUE THREAD

**Issue by charlinergr** [IBM/tensorflow-large-model-support#39] opened 2020-05-27 15:15 UTC
Hi !

I'm struggeling to use tensorflow-gpu from the WML CE channel.

I follow all the steps describe in : https://www.ibm.com/support/knowledgecenter/SS5SF7_1.7.0/navigation/wmlce_install.htm

Then, I run:
```python
>> import tensorflow as tf
2020-05-27 16:59:08.988965: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.2
2020-05-27 16:59:34.412988: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.7
2020-05-27 16:59:34.730903: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.7
>>> tf.config.experimental.set_lms_enabled(True)
```

which mean the installation work well, right ?

But when I run my code I got this issue: `SystemError: <built-in function len> returned a result with an error set` which I have not in TF2.1 without large model.

```python
Traceback (most recent call last):
  File "train_nx_graph_param.py", line 198, in <module>
    outputs_tr, loss_tr = compiled_update_step(input_graphs, target_graphs)
  File "/sps/l2it/crougier/conda/envs/tflm/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/sps/l2it/crougier/conda/envs/tflm/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 615, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/sps/l2it/crougier/conda/envs/tflm/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 497, in _initialize
    *args, **kwds))
  File "/sps/l2it/crougier/conda/envs/tflm/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2389, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/sps/l2it/crougier/conda/envs/tflm/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/sps/l2it/crougier/conda/envs/tflm/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/sps/l2it/crougier/conda/envs/tflm/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/sps/l2it/crougier/conda/envs/tflm/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 439, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/sps/l2it/crougier/conda/envs/tflm/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/sps/l2it/crougier/conda/envs/tflm/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 615, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/sps/l2it/crougier/conda/envs/tflm/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 497, in _initialize
    *args, **kwds))
  File "/sps/l2it/crougier/conda/envs/tflm/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2389, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/sps/l2it/crougier/conda/envs/tflm/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/sps/l2it/crougier/conda/envs/tflm/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/sps/l2it/crougier/conda/envs/tflm/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/sps/l2it/crougier/conda/envs/tflm/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 439, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/sps/l2it/crougier/conda/envs/tflm/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
tensorflow.python.autograph.impl.api.StagingError: in converted code:

    train_nx_graph_param.py:127 update_step  *
        grad = tape.gradient(loss_tr, model.variables)#,unconnected_gradients='none')
    /sps/l2it/crougier/conda/envs/tflm/lib/python3.7/site-packages/tensorflow_core/python/eager/backprop.py:1029 gradient
        unconnected_gradients=unconnected_gradients)
    /sps/l2it/crougier/conda/envs/tflm/lib/python3.7/site-packages/tensorflow_core/python/eager/imperative_grad.py:77 imperative_grad
        compat.as_str(unconnected_gradients.value))
    /sps/l2it/crougier/conda/envs/tflm/lib/python3.7/site-packages/tensorflow_core/python/eager/backprop.py:609 _aggregate_grads
        if len(gradients) == 1:

    SystemError: <built-in function len> returned a result with an error set
```

Did I do something wrong ? I suppose that I did not understand something as it is working in another environnement.

**Comment by jayfurmanek** [comment] 2020-05-27 15:26
Hi. Can you share the code you ran to get this error?

**Comment by charlinergr** [comment] 2020-05-27 15:33
Yes I can:

```python
if __name__ == "__main__":

    time_depart=time.time()

    # default 2/3 for training and 1/3 for testing
    input_nxgraphs_dir = '/sps/l2it/crougier/exatrkx-neurips19/TF2_tracking/out/nxgraphs_100'#without_section
    generate_input_target = prepare.inputs_generator(input_nxgraphs_dir, n_train_fraction=0.8)

    # How much time between logging and printing the current results.
    # save checkpoint very 10 mins
    log_every_seconds       = 10
    batch_size = n_graphs   = 4   # need optimization
    num_training_iterations = 10000
    iter_per_job            = 10000
    num_processing_steps_tr = 8   ## level of message-passing
    print("Maximum iterations per job: {}".format(iter_per_job))

    ###########
    ####Code essai pour TF2
    ###########
    
    # Dossier dans lequel on sauvegarde les checkpoints
    checkpoint_dir = '/sps/l2it/crougier/exatrkx-neurips19/TF2_tracking/out/TF2/default_10000'

    # Nom des fichiers checkpoint
    checkpoint_prefix = os.path.join(checkpoint_dir, ckpt_name)
    model =get_model('default')
    
    learning_rate = 1e-3
    optimizer = snt.optimizers.Adam(learning_rate)
    start_learning_rate = 0.001

    def create_loss_ops(target_op, output_ops, weights):

        # only use edges
        loss_ops = [
            tf.compat.v1.losses.log_loss(target_op.edges, output_op.edges, weights=weights)
            for output_op in output_ops
        ]
        return loss_ops

    @tf.function
    def update_step(inputs_tr, targets_tr):
        with tf.GradientTape() as tape:
            outputs_tr = model(inputs_tr, num_processing_steps_tr)
            real_weight = 1.0
            fake_weight = 0.5
            loss_weights = targets_tr.edges * real_weight + (1 - targets_tr.edges)*fake_weight
            loss_tr = create_loss_ops(targets_tr, outputs_tr,loss_weights)
            loss_tr = sum(loss_tr) / num_processing_steps_tr
            grad = tape.gradient(loss_tr, model.variables)#,unconnected_gradients='none')
        optimizer.apply(grad, model.trainable_variables)

        return outputs_tr, loss_tr

   
    ######
    input_graphs, target_graphs = generate_input_target(n_graphs)
    data=utils_tf.data_dicts_to_graphs_tuple(input_graphs)
    data2=utils_tf.data_dicts_to_graphs_tuple(target_graphs)
    example_graphs_tuple = data
    example_graphs_tuple2 = data2
    compiled_update_step = tf.function(update_step,input_signature=[utils_tf.specs_from_graphs_tuple(example_graphs_tuple),utils_tf.specs_from_graphs_tuple(example_graphs_tuple2)])
   
    
    checkpoint = tf.train.Checkpoint(optimizer=optimizer, model=model)
    iruns = 0
    last_iteration=0 #mettre en place récupération old checkpoints
    start_time = time.time()
    last_log_time = start_time
    for iteration in range(last_iteration, num_training_iterations):
        
        if iruns > iter_per_job:
            print("runs larger than {} iterations per job, stop".format(iter_per_job))
            break
        else: iruns += 1

        input_graphs, target_graphs = generate_input_target(n_graphs)
        input_graphs=utils_tf.data_dicts_to_graphs_tuple(input_graphs)
        target_graphs=utils_tf.data_dicts_to_graphs_tuple(target_graphs)

        outputs_tr, loss_tr = compiled_update_step(input_graphs, target_graphs)
        the_time = time.time()
        elapsed_since_last_log = the_time - last_log_time
        if elapsed_since_last_log > log_every_seconds:
            print('Checkpoint save, iteration {}'.format(iteration))
            last_log_time = the_time
            #checkpoint.write(file_prefix=checkpoint_prefix.format(iteration))
            checkpoint.save(file_prefix=checkpoint_prefix.format(iteration))
    checkpoint.save(file_prefix=checkpoint_prefix.format(iteration))
    print(time.time()- time_depart)
```

**Comment by smatzek** [comment] 2020-05-27 15:36
Does this error happen if using the WML CE tensorflow-gpu if you do not call `tf.config.experimental.set_lms_enabled(True)`?

**Comment by charlinergr** [comment] 2020-05-27 15:39
yes !

**Comment by jayfurmanek** [comment] 2020-05-27 17:09
Thank you! This looks like a snippet of a larger program. It will help if you have a self contained reproducible script. Is that possible?

Can you also post the output of `conda list`?  

Thanks.

**Comment by jayfurmanek** [comment] 2020-05-27 17:45
The above matches with the description of this issue:

https://github.com/tensorflow/tensorflow/issues/31962

Which was fixed in this commit:

https://github.com/tensorflow/tensorflow/commit/92af5842b003b8e223859bed4f0dabed400ede0f

Which didn't make it into 2.1.

You can apply that code change to your installation to see. Please report back if that does indeed fix your issue. There are other workarounds posted in that issue above (include removing the @tf.function declaration) that are worth trying as well.

If this fixes your error, this is certainly a candidate for a back-port fix. Thanks for reporting.

**Comment by charlinergr** [comment] 2020-05-28 08:14
The change in https://github.com/tensorflow/tensorflow/commit/92af5842b003b8e223859bed4f0dabed400ede0f seems already done on the tensorflow 2.1 from IBM.


I change the 
```python
tf.GradientTape()
```
by
```python
tf.gradients
```

and it works just fine now.

Thank you for the help !

**Closed as completed** 2020-06-05 12:24 UTC
